--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      none
-- Project :      ModelRelacional.DM1
-- Author :       amaury
--
-- Date Created : Wednesday, June 08, 2022 11:33:49
-- Target DBMS : Oracle 11g
--


-- 
-- sequence:  CATALOGO_BANCO_I_SEQ
--

CREATE SEQUENCE CATALOGO_BANCO_I_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    NOCYCLE
    ORDER
;

-- 
-- sequence:  HISTORICO_STATUS_PRESTAMO_SEQ
--

CREATE SEQUENCE HISTORICO_STATUS_PRESTAMO_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    NOCYCLE
    ORDER
;


-- 
-- sequence:  STATUS_SOLICITUD_SEQ
--

CREATE SEQUENCE STATUS_SOLICITUD_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    NOCYCLE
    ORDER
;


-- 
-- sequence:  PRESTAMO_SEQ
--

CREATE SEQUENCE PRESTAMO_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    NOCYCLE
    ORDER
;


-- 
-- sequence:  OCUPACION
--

CREATE SEQUENCE OCUPACION_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    NOCYCLE
    ORDER
;



-- 
-- TABLE: CARGO_TARJETA 
--

CREATE TABLE CARGO_TARJETA(
    FOLIO_OPERACION    VARCHAR2(8)      NOT NULL,
    IMPORTE            NUMBER(10, 3)    NOT NULL,
    FECHA              DATE             NOT NULL,
    NUMERO_TARJETA     NUMBER(16, 0)    NOT NULL,
    CONSTRAINT CARGO_TARJETA_FOLIO_OPERACION_ID_PK PRIMARY KEY (FOLIO_OPERACION)
    USING INDEX(
        CREATE UNIQUE INDEX CARGO_TARJETA_FOLIO_OPERACION_PK_IDX ON CARGO_TARJETA(FOLIO_OPERACION)
        TABLESPACE tbs_indexes
    ),
    CONSTRAINT CARGO_TARJETA_NUMERO_TARJETA_FK FOREIGN KEY (NUMERO_TARJETA)
    REFERENCES TARJETA(NUMERO_TARJETA)
    USING INDEX(
        CREATE INDEX CARGO_TARJETA_FECHA_NUK_IDX ON CARGO_TARJETA(FECHA)
        TABLESPACE tbs_indexes
    ),
    USING INDEX (
        CREATE INDEX CARGO_TARJETA_NUMERO_TARJETA_FK_IDX ON CARGO_TARJETA(NUMERO_TARJETA)
    )
) TABLESPACE tbs_cuentaInversionista_encrypt
;



-- 
-- TABLE: CATALOGO_BANCO_I 
--

CREATE TABLE CATALOGO_BANCO_I(
    CATALOGO_BANCO_I_ID    NUMBER(3, 0)    NOT NULL,
    NOMBRE                 VARCHAR2(60)    NOT NULL,
    CONSTRAINT CATALOGO_BANCO_I_ID_PK PRIMARY KEY (CATALOGO_BANCO_I_ID)
    USING INDEX (
        CREATE UNIQUE INDEX CATALOGO_BANCO_I_CATALOGO_BANCO_I_ID_PK_IDX ON CATALOGO_BANCO_I(CATALOGO_BANCO_I_ID)
        TABLESPACE tbs_indexes
    )
)TABLESPACE tbs_inversionista 
;



-- 
-- TABLE: CATALOGO_BANCO_S 
--

CREATE TABLE CATALOGO_BANCO_S(
    CATALOGO_BANCO_S_ID    NUMBER(3, 0)    NOT NULL,
    NOMBRE                 VARCHAR2(60)    NOT NULL,
    CONSTRAINT CATALOGO_BANCO_S_ID_PK PRIMARY KEY (CATALOGO_BANCO_S_ID)
    USING INDEX(
        CREATE UNIQUE INDEX CATALOGO_BANCO_S_CATALOGO_BANCO_S_ID_PK_IDX ON CATALOGO_BANCO_S(CATALOGO_BANCO_S_ID)
        TABLESPACE tbs_indexes
    )TABLESPACE tbs_cuentaSolicitante_encrypt
)
;



-- 
-- TABLE: CUENTA_INVERSIONISTA 
--

CREATE TABLE CUENTA_INVERSIONISTA(
    CUENTA_INVERSIONISTA_ID    NUMBER(38, 0)    NOT NULL,
    CLABE                      NUMBER(18, 0)    NOT NULL,
    TITULAR                    VARCHAR2(80)     NOT NULL,
    CATALOGO_BANCO_I_ID        NUMBER(3, 0)     NOT NULL,
    CONSTRAINT CUENTA_INVERSIONISTA_CUENTA_INVERSIONISTA_ID_PK PRIMARY KEY (CUENTA_INVERSIONISTA_ID)
    USING INDEX(
        CREATE UNIQUE INDEX CUENTA_INVERSIONISTA_CUENTA_INVERSIONISTA_ID_PK_IDX ON CUENTA_INVERSIONISTA(CUENTA_INVERSIONISTA_ID)
        TABLESPACE tbs_indexes
    ),
    USING INDEX(
        CREATE UNIQUE INDEX CUENTA_INVERSIONISTA_CLABE_UK_IDX ON CUENTA_INVERSIONISTA(CLABE)
        TABLESPACE tbs_indexes
    ),
    USING INDEX(
        CREATE INDEX CUENTA_INVERSIONISTA_BF_LOWWER_IDX ON CUENTA_INVERSIONISTA(LOWWER(TITULAR))
        TABLESPACE tbs_indexes
    ),
    USING INDEX(
        CREATE INDEX CUENTA_INVERSIONISTA_CATALOGO_BANCO_BANCO_I_ID_FK_IDX ON CUENTA_INVERSIONISTA(CATALOGO_BANCO_I_ID)
        TABLESPACE tbs_indexes
    ),
    CONSTRAINT CUENTA_INVERSIONISTA_CATALOGO_BANCO_I_FK FOREIGN KEY (CATALOGO_BANCO_I)
    REFERENCES CATALOGO_BANCO_I(CATALOGO_BANCO_I_ID) 
)TABLESPACE tbs_cuentaInversionista_encrypt
;



-- 
-- TABLE: CUENTA_SOLICITANTE 
--

CREATE TABLE CUENTA_SOLICITANTE(
    CUENTA_SOLICITANTE_ID    NUMBER(38, 0)    NOT NULL,
    CLABE                    NUMBER(18, 0)    NOT NULL,
    TITULAR                  VARCHAR2(80)     NOT NULL,
    CATALOGO_BANCO_S_ID      NUMBER(3, 0)     NOT NULL,
    USUARIO_ID               NUMBER(38, 0)    NOT NULL,
    CONSTRAINT CUENTA_SOLICITANTE_CUENTA_SOLICITANTE_ID_PK PRIMARY KEY (CUENTA_SOLICITANTE_ID)
    USING INDEX(
        CREATE UNIQUE INDEX CUENTA_SOLICITANTE_CUENTA_SOLICITABTE_ID_PK_IDX ON CUENTA_SOLICITANTE(CUENTA_SOLICITANTE_ID)
        TABLESPACE tbs_indexes
    ),
    USING INDEX(
        CREATE INDEX CUENTA_SOLICITANTE_CATALOGO_BANCO_S_ID_FK_IDX ON CUENTA_SOLICITANTE(CATALOGO_BANCO_S_ID)
        TABLESPACE tbs_indexes
    ),
    USING INDEX(
        CREATE INDEX CUENTA_SOLICITANTE_USUARIO_ID_FK_IDX ON CUENTA_SOLICITANTE(USUARIO_ID)
        TABLESPACE tbs_indexes
    ),
    CONSTRAINT CUENTA_SOLICITANTE_CATALOGO_BANCO_S_ID_FK FOREIGN KEY (CATALOGO_BANCO_S_ID)
    REFERENCES CATALOGO_BANCO_S(CATALOGO_BANCO_S_ID),
    CONSTRAINT CUENTA_SOLICITANTE_USUARIO_ID_FK FOREIGN KEY (USAURIO_ID)
    REFERENCES SOLICITANTE(USUARIO_ID)
)TABLESPACE tbs_cuentaSolicitante_encrypt
;



-- 
-- TABLE: GANANCIA_MENSUAL 
--

CREATE TABLE GANANCIA_MENSUAL(
    GANANCIA_MENSUAL_ID        NUMBER(38, 0)    NOT NULL,
    GANANCIA_MENSUAL           NUMBER(38, 0),
    IMPORTE_TOTAL              NUMBER(38, 0),
    FECHA_DEPOSITO             DATE,
    RECIBO_DEPOSITO            BLOB,
    PAGO_ANUAL                 NUMBER(38, 0),
    USUARIO_ID                 NUMBER(38, 0)    NOT NULL,
    CUENTA_INVERSIONISTA_ID    NUMBER(38, 0)    NOT NULL,
    CONSTRAINT GANANCIA_MENSUAL_GANANCIA_MENSUAL_ID_PK PRIMARY KEY (GANANCIA_MENSUAL_ID)
    USING UNIQUE INDEX(
        CREATE UNIQUE INDEX GANANCIA_MENSUAL_GANANCIA_MENSUAL_ID_PK_IDX ON GANANCIA_MENSUAL(GANANCIA_MENSUAL_ID)
        TABLESPACE tbs_indexes
    ),
    CONSTRAINT GANANCIA_MENSUAL_USUARIO_ID_FK FOREIGN KEY(USAURIO_ID)
    REFERENCES INVERSIONISTA(USUARIO_ID)
    USING INDEX(
        CREATE INDEX GANANCIA_MENSUAL_USUARIO_ID_FK_IDX ON GANANCIA_MENSUAL(USUARIO_ID)
        TABLESPACE tbs_indexes
    ), 
    CONSTRAINT GANANCIA_MENSUAL_CUENTA_INVERSIONISTA_ID_FK FOREIGN KEY (CUENTA_INVERSIONISTA)
    REFERENCES CUENTA_INVERSIONISTA(CUENTA_INVERSIONISTA_ID)
    USING INDEX(
        CREATE INDEX GANANCIA_MENSUAL_CUENTA_INVERSIONISTA_ID_FK_IDX ON GANANCIA_MENSUAL(CUENTA_INVERSIONISTA_ID)
        TABLESPACE tbs_indexes
    )
)TABLESPACE tbs_inversionista LOB (RECIBO_DEPOSITO) STORE AS (TABLESPACE tbs_blob_mod1)
;


-- 
-- TABLE: HISTORICO_STATUS_PRESTAMO 
--

CREATE TABLE HISTORICO_STATUS_PRESTAMO(
    HISTORICO_STATUS_PRESTAMO_ID    NUMBER(5, 0)     NOT NULL,
    FECHA_STATUS                    DATE             NOT NULL,
    MONTO_SOLICITADO                NUMBER(9, 2)     NOT NULL,
    FECHA_SOLICITUD                 DATE             NOT NULL,
    STATUS_SOLICITUD_ID             NUMBER(3, 0)     NOT NULL,
    PRESTAMO_ID                     NUMBER(38, 0)    NOT NULL,
    CONSTRAINT HISTORICO_STATUS_PRESTAMO_HISTORICO_STATUS_PRESTAMO_ID_PK PRIMARY KEY (HISTORICO_STATUS_PRESTAMO_ID)
    USING INDEX(
        CREATE UNIQUE INDEX HISTORICO_STATUS_PRESTAMO_HISTORICO_STATUS_PRESTAMO_ID_PK_IDX ON HISTORICO_STATUS_PRESTAMO(HISTORICO_STATUS_PRESTAMO_ID)
        TABLESPACE tbs_indexes
    ),
    CONSTRAINT HISTORICO_STATUS_PRESTAMO_STATUS_SOLICITUD_ID_FK FOREIGN KEY (STATUS_SOLICITUD_ID)
    REFERENCES STATUS_SOLICITUD(STATUS_SOLICITUD_ID)
    USING INDEX(
        CREATE INDEX HISTORICO_STATUS_PRESTAMO_STATUS_SOLICITUD_ID_FK_IDX ON HISTORICO_STATUS_PRESTAMO(STATUS_SOLICITUD_ID)
        TABLESPACE tbs_indexes
    ),
    CONSTRAINT HISTORICO_STATUS_PRESTAMO_PRESTAMO_ID_FK FOREIGN KEY (PRESTAMO_ID)
    REFERENCES PRESTAMO(PRESTAMO_ID)
    USING INDEX(
        CREATE INDEX HISTORICO_STATUS_PRESTAMO_PRESTAMO_ID_FK_IDX ON HISTORICO_STATUS_PRESTAMO(PRESTAMO_ID)
        TABLESPACE tbs_indexes
    )
)TABLESPACE tbs_solicitantePrestamo
;



-- 
-- TABLE: INVERSIONISTA 
--

CREATE TABLE INVERSIONISTA(
    USUARIO_ID          NUMBER(38, 0)    NOT NULL,
    MONTO_MENSUAL       NUMBER(9, 2)     NOT NULL,
    DIACARGO_TARJETA    NUMBER(2, 0)     NOT NULL,
    HABILITADO          NUMBER(1, 0)     NOT NULL,
    PUNTAJE_TOTAL       NUMBER(2, 0)     NOT NULL,
    ES_REVISOR          NUMBER(1, 0)     NOT NULL,
    CONSTRAINT INVERSIONISTA_USUARIO_ID_PK PRIMARY KEY (USUARIO_ID)
    USING INDEX(
        CREATE UNIQUE INDEX INVERSIONISTA_USUARIO_ID_PK_IDX ON INVERSIONISTA(USUARIO_ID)
        TABLESPACE tbs_indexes
    ),
    CONSTRAINT INVERSIONISTA_USUARIO_ID_FK FOREIGN KEY (USUARIO_ID)
    REFERENCES USUARIO(USUARIO_ID)
)TABLESPACE tbs_inversionista
;




-- 
-- TABLE: OCUPACION 
--

CREATE TABLE OCUPACION(
    OCUPACION_ID    NUMBER(300, 0)    NOT NULL,
    OCUPACION       VARCHAR2(50)      NOT NULL,
    CONSTRAINT OCUPACION_OCUPACION_ID_PK PRIMARY KEY (OCUPACION_ID)
    USING UNIQUE INDEX(
        CREATE UNIQUE INDEX OCUPACION_OCUPACION_ID_PK_IDX ON OCUPACION(OCUPACION_ID)
        TABLESPACE tbs_indexes
    )
)TABLESPACE tbs_solicitantePrestamo
;


-- 
-- TABLE: PAGO_PRESTAMO 
--

CREATE TABLE PAGO_PRESTAMO(
    PAGO_PRESTAMO_ID     NUMBER(38, 0)    NOT NULL,
    FECHA_PAGO           DATE             NOT NULL,
    COMPROBANTE_PAGO     BLOB,
    CALIFICACION         NUMBER(1, 0),
    IMPORTE_PAGO         NUMBER(6, 0)     NOT NULL,
    FECHA_MAXIMA_PAGO    DATE             NOT NULL,
    PRESTAMO_ID          NUMBER(38, 0)    NOT NULL,
    CONSTRAINT PAGO_PRESTAMO_PAGO_PRESTAMO_ID_PK PRIMARY KEY (PAGO_PRESTAMO_ID)
    USING UNIQUE INDEX(
        CREATE UNIQUE INDEX PAGO_PRESTAMO_PAGO_PRESTAMO_ID_PK_IDX ON PAGO_PRESTAMO(PAGO_PRESTAMO_ID)
        TABLESPACE tbs_indexes
    ),
    CONSTRAINT PAGO_PRESTAMO_PRESTAMO_ID_FK FOREIGN KEY (PRESTAMO_ID)
    REFERENCES PRESTAMO(PRESTAMO_ID)
    USING INDEX(
        CREATE INDEX PAGO_PRESTAMO_PRESTAMO_ID_FK_IDX ON PAGO_PRESTAMO(PRESTAMO_ID)
        TABLESPACE tbs_indexes
    ),
    USING INDEX(
        CREATE INDEX PAGO_PRESTAMO_FECHA_PAGO_NUK_IDX ON PAGO_PRESTAMO(FECHA_PAGO)
        TABLESPACE tbs_indexes
    )

)TABLESPACE tbs_pago LOB (COMPROBANTE_PAGO) STORE AS (tbs_blob_mod2)
;


-- 
-- TABLE: PERFIL_ANUAL 
--

CREATE TABLE PERFIL_ANUAL(
    PERFIL_ANUAL_ID         NUMBER(38, 0)    NOT NULL,
    PAGO_TIEMPO_ANTICIPO    NUMBER(38, 0),
    PRESTAMO_SOLICITADO     NUMBER(38, 0),
    PRESTAMO_AUTORIZADO     NUMBER(38, 0),
    PRESTAMO_RECHAZADO      NUMBER(38, 0),
    PAGO_DESTIEMPO          NUMBER(38, 0),
    USUARIO_ID              NUMBER(38, 0)    NOT NULL,
    CONSTRAINT PERFIL_ANUAL_PERFIL_ANUAL_ID_PK PRIMARY KEY (PERFIL_ANUAL_ID)
    USING INDEX(
        CREATE UNIQUE INDEX PERFIL_ANUAL_PERFIL_ANUAL_ID_PK_IDX ON PERFIL_ANUAL(PERFIL_ANUAL_ID)
        TABLESPACE tbs_indexes
    ),
    CONSTRAINT PERFIL_ANUAL_USUARIO_ID_FK FOREIGN KEY (USUARIO_ID)
    REFERENCES SOLICITANTE(USUARIO_ID)
    USING INDEX(
        CREATE INDEX PERFIL_ANUAL_USUARIO_ID_FK_IDX ON PERFIL_ANUAL(USUARIO_ID)
        TABLESPACE tbs_indexes
    )
    
)TABLESPACE tbs_usuario
;



-- 
-- TABLE: PRESTAMO _-------------LSITO
--

CREATE TABLE PRESTAMO(
    PRESTAMO_ID            NUMBER(38, 0)    NOT NULL,
    PORCENTAGE_INTERES     NUMBER(3, 1)     NOT NULL,
    FECHA_SOLICITUD        DATE             NOT NULL,
    MONTO_SOLICITADO       NUMBER(9, 2)     NOT NULL,
    NUMERO_PAGOS           NUMBER(2, 0)     NOT NULL,
    MODO_PAGO              NUMBER(1, 0)     NOT NULL,
    USUARIO_ID             NUMBER(38, 0)    NOT NULL,
    STATUS_SOLICITUD_ID    NUMBER(3, 0)     NOT NULL,
    FECHA_STATUS           DATE             NOT NULL,
    CONSTRAINT PRESTAMO_PRESTAMO_ID_PK PRIMARY KEY (PRESTAMO_ID)
    USING INDEX(
        CREATE UNIQUE INDEX PRESTAMO_PRESTAMO_ID_PK_IDX ON PRESTAMO(PRESTAMO_ID)
        TABLESPACE tbs_indexes
    ),
    CONSTRAINT PRESTAMO_USUARIO_ID_FK FOREIGN KEY (USUARIO_ID)
    REFERENCES SOLICITANTE(USUARIO_ID)
    USING INDEX(
        CREATE INDEX PRESTAMO_USUARIO_ID_FK_IDX ON PRESTAMO(USUARIO_ID)
        TABLESPACE tbs_indexes
    ),
    CONSTRAINT PRESTAMO_STATUS_SOLICITUD_ID_FK FOREIGN KEY (STATUS_SOLICITUD_ID)
    REFERENCES STATUS_SOLICITUD(STATUS_SOLICITUD_ID)
    USING INDEX(
        CREATE INDEX PRESTAMO_STATUS_SOLICITUD_ID_FK_IDX ON PRESTAMO(STATUS_SOLICITUD_ID)
        TABLESPACE tbs_indexes
    ),
    USING INDEX(
        CREATE INDEX PRESTAMO_FECHA_SOLICITUD_NUK_IDX ON PRESTAMO(FECHA_SOLICITUD)
        TABLESPACE tbs_indexes
    )
)TABLESPACE tbs_solicitantePrestamo
;

-- 
-- TABLE: PUNTAJE_INVERSIONISTA 
--

CREATE TABLE PUNTAJE_INVERSIONISTA(
    USUARIO_ID          NUMBER(38, 0)    NOT NULL,
    PRESTAMO_ID         NUMBER(38, 0)    NOT NULL,
    PUNTOS_NEGATIVOS    NUMBER(2, 0)     NOT NULL,
    PUNTOS_FECHA        DATE             NOT NULL,
    DESCRIPCION         VARCHAR2(150)    NOT NULL,
    CONSTRAINT PUNTAJE_INVERSIONISTA_ID_PK PRIMARY KEY (USUARIO_ID, PRESTAMO_ID)
    USING INDEX(
        CREATE INDEX PUNTAJE_INVERSIONISTA_PK_IDX ON PUNTAJE_INVERSIONISTA(USUARIO_ID, PRESTAMO_ID)
        TABLESPACE tbs_indexes
    ),
    CONSTRAINT PUNTAJE_INVERSIONISTA_FK FOREIGN KEY (USUARIO_ID, PRESTAMO_ID)
    REFERENCES VOTO_INVERSIONISTA(USUARIO_ID, PRESTAMO_ID)
)TABLESPACE tbs_inversionista



-- 
-- TABLE: SOLICITANTE 
--

CREATE TABLE SOLICITANTE(
    USUARIO_ID               NUMBER(38, 0)     NOT NULL,
    IDUSUARIOAVAL            NUMBER(38, 0),
    IDENTIFICACION           BLOB              NOT NULL,
    COMPROBANTE_DOMICILIO    BLOB              NOT NULL,
    FOTO                     BLOB              NOT NULL,
    DIRECCION                VARCHAR2(100)     NOT NULL,
    SITIO_WEB                VARCHAR2(120)     NOT NULL,
    OCUPACION_ID             NUMBER(300, 0)    NOT NULL,
    CONSTRAINT SOLICITANTE_USUARIO_ID_PK PRIMARY KEY (USUARIO_ID)
    USING INDEX(
        CREATE UNIQUE INDEX SOLICITANTE_USUARIO_ID_PK_IDX ON SOLICITANTE(USUARIO_ID)
        TABLESPACE tbs_indexes
    ),
    CONSTRAINT SOLICITANTE_SOLICITANTE_USAURIO_ID_FK FOREIGN KEY (USUARIO_ID)
    REFERENCES USUARIO(USAURIO_ID),
    CONSTRAINT SOLICITANTE_OCUPACION_ID_FK FOREIGN KEY (OCUPACION_ID)
    REFERENCES OCUPACION(OCUPACION_ID)
    USING INDEX(
        CREATE INDEX SOLICITANTE_OCUPACION_ID_FK_IDX ON SOLICITANTE(OCUPACION_ID)
        TABLESPACE tbs_indexes
    ),
    CONSTRAINT SOLICITANTE_IDUSUARIOAVAL_FK FOREIGN KEY (IDUSUARIOAVAL)
    REFERENCES SOLICITANTE(USUARIO_ID)
)TABLESPACE tbs_solicitantePrestamo LOB (IDENTIFICACION, COMPROBANTE_DOMICILIO, FOTO) AS (TABLESPACE tbs_blob_mod2)
;





-- 
-- TABLE: STATUS_SOLICITUD 
--

CREATE TABLE STATUS_SOLICITUD(
    STATUS_SOLICITUD_ID    NUMBER(3, 0)     NOT NULL,
    DESCRIPCION            VARCHAR2(200)    NOT NULL,
    TIPO                   VARCHAR2(20)     NOT NULL,
    CONSTRAINT STATUS_SOLICITUD_STATUS_SOLICITUD_ID_PK PRIMARY KEY (STATUS_SOLICITUD_ID)
    USING INDEX(
        CREATE UNIQUE INDEX STATUS_SOLICITUD_STATUS_SOLICITUD_ID_PK_IDX ON STATUS_SOLICITUD(STATUS_SOLICITUD_ID)
        TABLESPACE tbs_indexes
    )
)TABLESPACE tbs_solicitantePrestamo
;



-- 
-- TABLE: TARJETA 
--

CREATE TABLE TARJETA(
    NUMERO_TARJETA      NUMBER(16, 0)    NOT NULL,
    MES                 NUMBER(2, 0)     NOT NULL,
    NUMERO_SEGURIDAD    NUMBER(3, 0)     NOT NULL,
    ANIO                 NUMBER(4, 0)     NOT NULL,
    USUARIO_ID          NUMBER(38, 0)    NOT NULL,
    CONSTRAINT TARJETA_NUMERO_TARJETA_PK PRIMARY KEY (NUMERO_TARJETA)
    USING INDEX(
        CREATE UNIQUE INDEX TARJETA_NUMERO_TARJETA_PK_IDX ON TARJETA(NUMERO_TARJETA)
        TABLESPACE tbs_indexes
    ),
    CONSTRAINT TARJETA_USUARIO_ID_FK FOREIGN KEY(USUARIO_ID)
    REFERENCES INVERSIONISTA(USUARIO_ID)
    USING INDEX(
        CREATE UNIQUE INDEX TARJETA_USUARIO_ID_FK_IDX ON TARJETA(USUARIO_ID)
        TABLESPACE tbs_indexes
    )

)TABLESPACE tbs_cuentaInversionista_encrypt
;





-- 
-- TABLE: USUARIO 
--

CREATE TABLE USUARIO(
    USUARIO_ID          NUMBER(38, 0)    NOT NULL,
    NOMBRE_USUARIO      VARCHAR2(40)     NOT NULL,
    PASSWORD            VARCHAR2(20)     NOT NULL,
    NOMBRE              VARCHAR2(30)     NOT NULL,
    AP_PATERNO          VARCHAR2(30)     NOT NULL,
    AP_MATERNO          VARCHAR2(30)     NOT NULL,
    CURP                VARCHAR2(18)     NOT NULL,
    RFC                 VARCHAR2(13)     NOT NULL,
    FECHA_NACIMINETO    DATE             NOT NULL,
    ES_SOLICITANTE      NUMBER(1, 0)     NOT NULL,
    ES_INVERSOR         NUMBER(1, 0)     NOT NULL,
    CONSTRAINT USUARIO_USUARIO_ID_PK PRIMARY KEY (USUARIO_ID)
    USING INDEX(
        CREATE UNIQUE INDEX USUARIO_USUARIO_ID_PK_IDX ON USUARIO(USUARIO_ID)
        TABLESPACE tbs_indexes
    ),
    USING INDEX(
        CREATE UNIQUE INDEX USUARIO_NOMBRE_USUARIO_UK_IDX ON USUARIO(NOMBRE_USUARIO)
        TABLESPACE tbs_indexes
    ),
    USING INDEX(
        CREATE UNIQUE INDEX USUARIO_CURP_UK_IDX ON USUARIO(CURP)
        TABLESPACE tbs_indexes
    ),
    USING INDEX(
        CREATE UNIQUE INDEX USUARIO_RFC_UK_IDX ON USUARIO(RFC)
        TABLESPACE tbs_indexes
    )
)TABLESPACE tbs_usuario
;



-- 
-- TABLE: USUARIO_COMENTARIO 
--

CREATE TABLE USUARIO_COMENTARIO(
    USUARIO_COMENTARIO_ID    NUMBER(38, 0)    NOT NULL,
    USUARIO_COMENTADO        NUMBER(38, 0)    NOT NULL,
    USUARIO_ID               NUMBER(38, 0)    NOT NULL,
    COMENTARIO               VARCHAR2(150)    NOT NULL,
    CONSTRAINT USUARIO_COMENTARIO_USAURIO_COMENTARIO_ID_PK PRIMARY KEY (USUARIO_COMENTARIO_ID)
    USING INDEX(
        CREATE UNIQUE INDEX USUARIO_COMENTARIO_USAURIO_COMENTARIO_ID_PK_IDX ON USUARIO_COMENTARIO(USUARIO_COMENTARIO_ID)
        TABLESPACE tbs_indexes
    ),
    CONSTRAINT USUARIO_COMENTARIO_USUARIO_COMENTADO_FK FOREIGN KEY (USUARIO_COMENTADO)
    REFERENCES USUARIO(USUARIO_ID),
    CONSTRAINT USUARIO_COMENTARIO_USUARIO_ID_COMENTADOR_FK FOREIGN KEY (USUARIO_ID)
    REFERENCES USUARIO(USUARIO_ID)
)TABLESPACE tbs_usuario
;




-- 
-- TABLE: VOTO_INVERSIONISTA 
--

CREATE TABLE VOTO_INVERSIONISTA(
    USUARIO_ID            NUMBER(38, 0)    NOT NULL,
    PRESTAMO_ID           NUMBER(38, 0)    NOT NULL,
    VOTO_OBTENIDO         NUMBER(1, 0),
    FECHA_VOTO            DATE,
    JUSTIFICACION_VOTO    VARCHAR2(120),
    CONSTRAINT VOTO_INVERSIONISTA_PK PRIMARY KEY (USUARIO_ID, PRESTAMO_ID)
    USING INDEX(
        CREATE UNIQUE INDEX VOTO_INVERSIONISTA_PK_IDX ON VOTO_INVERSIONISTA(USUARIO_ID, PRESTAMO_ID)
        TABLESPACE tbs_indexes
    )
)TABLESPACE tbs_inversionista
;



